<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        DB::table('stores')->insert([
            [
                'name' => 'Dapur Nusantara',
                'slug' => 'dapur-nusantara',
                'description' => 'Restoran khas Indonesia dengan berbagai menu tradisional dan modern.',
                'image' => null,
                'banner' => null,
                'address' => 'Jl. Ahmad Yani No. 12, Pontianak',
                'phone' => '081234567890',
                'latitude' => -0.02633000,
                'longitude' => 109.34250000,
                'is_open' => true,
                'closed_reason' => '',
                'accept_order' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Kopi Senja',
                'slug' => 'kopi-senja',
                'description' => 'Coffee shop modern dengan suasana nyaman untuk bekerja dan nongkrong.',
                'image' => null,
                'banner' => null,
                'address' => 'Jl. Gajah Mada No. 45, Pontianak',
                'phone' => '082345678901',
                'latitude' => -0.03021000,
                'longitude' => 109.34110000,
                'is_open' => true,
                'closed_reason' => '',
                'accept_order' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Ayam Geprek Mantap',
                'slug' => 'ayam-geprek-mantap',
                'description' => 'Tempat makan ayam geprek pedas dengan berbagai level sambal.',
                'image' => null,
                'banner' => null,
                'address' => 'Jl. Tanjungpura No. 88, Pontianak',
                'phone' => '083456789012',
                'latitude' => -0.02875000,
                'longitude' => 109.34490000,
                'is_open' => false,
                'closed_reason' => 'Tutup Sementara',
                'accept_order' => true,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('store_operating_hours')->insert([
            // Dapur Nusantara (store_id = 1)
            [
                'store_id' => 1,
                'day_of_week' => 0,
                'open_time' => '08:00:00',
                'close_time' => '21:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 1,
                'day_of_week' => 1,
                'open_time' => '08:00:00',
                'close_time' => '21:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 1,
                'day_of_week' => 2,
                'open_time' => '08:00:00',
                'close_time' => '21:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 1,
                'day_of_week' => 3,
                'open_time' => '08:00:00',
                'close_time' => '21:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 1,
                'day_of_week' => 4,
                'open_time' => '08:00:00',
                'close_time' => '21:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 1,
                'day_of_week' => 5,
                'open_time' => '08:00:00',
                'close_time' => '22:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 1,
                'day_of_week' => 6,
                'open_time' => '08:00:00',
                'close_time' => '22:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kopi Senja (store_id = 2)
            [
                'store_id' => 2,
                'day_of_week' => 0,
                'open_time' => '10:00:00',
                'close_time' => '23:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 2,
                'day_of_week' => 1,
                'open_time' => '08:00:00',
                'close_time' => '22:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 2,
                'day_of_week' => 2,
                'open_time' => '08:00:00',
                'close_time' => '22:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 2,
                'day_of_week' => 3,
                'open_time' => '08:00:00',
                'close_time' => '22:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 2,
                'day_of_week' => 4,
                'open_time' => '08:00:00',
                'close_time' => '22:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 2,
                'day_of_week' => 5,
                'open_time' => '08:00:00',
                'close_time' => '23:30:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 2,
                'day_of_week' => 6,
                'open_time' => '08:00:00',
                'close_time' => '23:30:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Ayam Geprek Mantap (store_id = 3)
            [
                'store_id' => 3,
                'day_of_week' => 0,
                'open_time' => null,
                'close_time' => null,
                'is_open' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 3,
                'day_of_week' => 1,
                'open_time' => '09:00:00',
                'close_time' => '20:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 3,
                'day_of_week' => 2,
                'open_time' => '09:00:00',
                'close_time' => '20:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 3,
                'day_of_week' => 3,
                'open_time' => '09:00:00',
                'close_time' => '20:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 3,
                'day_of_week' => 4,
                'open_time' => '09:00:00',
                'close_time' => '20:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 3,
                'day_of_week' => 5,
                'open_time' => '09:00:00',
                'close_time' => '21:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 3,
                'day_of_week' => 6,
                'open_time' => '09:00:00',
                'close_time' => '21:00:00',
                'is_open' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('menu_categories')->insert([
            [
                'store_id' => 1,
                'name' => 'Makanan Utama',
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 1,
                'name' => 'Minuman',
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 2,
                'name' => 'Coffee',
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 2,
                'name' => 'Non Coffee',
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 2,
                'name' => 'Snack',
                'sort_order' => 3,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 3,
                'name' => 'Ayam Geprek',
                'sort_order' => 1,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 3,
                'name' => 'Minuman',
                'sort_order' => 2,
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        DB::table('menus')->insert([

            [
                'store_id' => 1,
                'menu_category_id' => 1,
                'name' => 'Nasi Goreng Kampung',
                'description' => 'Nasi goreng dengan bumbu khas kampung.',
                'price' => 25000,
                'image' => null,
                'sort_order' => 1,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 1,
                'menu_category_id' => 1,
                'name' => 'Ayam Bakar Madu',
                'description' => 'Ayam bakar dengan saus madu spesial.',
                'price' => 35000,
                'image' => null,
                'sort_order' => 2,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 1,
                'menu_category_id' => 2,
                'name' => 'Es Teh Manis',
                'description' => 'Teh manis dingin segar.',
                'price' => 8000,
                'image' => null,
                'sort_order' => 1,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 1,
                'menu_category_id' => 2,
                'name' => 'Jeruk Peras',
                'description' => 'Jeruk segar tanpa pemanis buatan.',
                'price' => 12000,
                'image' => null,
                'sort_order' => 2,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 2,
                'menu_category_id' => 3,
                'name' => 'Americano',
                'description' => 'Kopi hitam dengan cita rasa kuat.',
                'price' => 22000,
                'image' => null,
                'sort_order' => 1,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 2,
                'menu_category_id' => 3,
                'name' => 'Cappuccino',
                'description' => 'Espresso dengan susu dan foam.',
                'price' => 28000,
                'image' => null,
                'sort_order' => 2,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 2,
                'menu_category_id' => 4,
                'name' => 'Chocolate Latte',
                'description' => 'Minuman coklat creamy.',
                'price' => 30000,
                'image' => null,
                'sort_order' => 1,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 2,
                'menu_category_id' => 5,
                'name' => 'French Fries',
                'description' => 'Kentang goreng crispy.',
                'price' => 18000,
                'image' => null,
                'sort_order' => 1,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 2,
                'menu_category_id' => 5,
                'name' => 'Croissant',
                'description' => 'Pastry butter premium.',
                'price' => 20000,
                'image' => null,
                'sort_order' => 2,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 3,
                'menu_category_id' => 6,
                'name' => 'Ayam Geprek Level 1',
                'description' => 'Ayam geprek dengan sambal level 1.',
                'price' => 18000,
                'image' => null,
                'sort_order' => 1,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 3,
                'menu_category_id' => 6,
                'name' => 'Ayam Geprek Level 5',
                'description' => 'Ayam geprek super pedas.',
                'price' => 22000,
                'image' => null,
                'sort_order' => 2,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 3,
                'menu_category_id' => 6,
                'name' => 'Ayam Geprek Keju',
                'description' => 'Ayam geprek dengan topping keju.',
                'price' => 25000,
                'image' => null,
                'sort_order' => 3,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'store_id' => 3,
                'menu_category_id' => 7,
                'name' => 'Es Teh Jumbo',
                'description' => 'Es teh ukuran besar.',
                'price' => 7000,
                'image' => null,
                'sort_order' => 1,
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
