services:
  # app:
  #   image: mfebrinugroho/kaserva-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile

  #   container_name: kaserva-api

  #   ports:
  #     - "8000:8000"

  #   volumes:
  #     - .:/var/www/html
  #     - vendor:/var/www/html/vendor

  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  #   restart: unless-stopped
  postgres:
    image: postgres:18
    container_name: kaserva-postgres

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  
    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_test:
    image: postgres:18
    container_name: kaserva-postgres-test

    ports:
      - "5433:5432"

    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
  
    volumes:
      - postgres_test_data:/var/lib/postgresql
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_TEST_USER} -d ${POSTGRES_TEST_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  postgres_test_data:
  # vendor: